package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ADCServiceForEC service = new ADCServiceForEC();
 * NGADCServiceForEC portType = service.getNGADCServicesForEC();
 * portType.adcServices(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ADCServiceForEC", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://221.179.7.247:8201/NGADCInterface/NGADCServicesForEC.svc?wsdl")
public class ADCServiceForEC extends Service {

	private final static URL ADCSERVICEFOREC_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.tempuri.ADCServiceForEC.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.ADCServiceForEC.class.getResource(".");
			url = new URL(baseUrl,
					"http://221.179.7.247:8201/NGADCInterface/NGADCServicesForEC.svc?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://221.179.7.250/NGADCInfcText/NGADCServicesForEC.svc?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ADCSERVICEFOREC_WSDL_LOCATION = url;
	}

	public ADCServiceForEC(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ADCServiceForEC() {
		super(ADCSERVICEFOREC_WSDL_LOCATION, new QName("http://tempuri.org/",
				"ADCServiceForEC"));
	}

	/**
	 * 
	 * @return returns NGADCServiceForEC
	 */
	@WebEndpoint(name = "NGADCServicesForEC")
	public NGADCServiceForEC getNGADCServicesForEC() {
		return super.getPort(new QName("http://tempuri.org/",
				"NGADCServicesForEC"), NGADCServiceForEC.class);
	}

}
