package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ecinterface.adc.NGEC;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "NGADCServiceForEC", targetNamespace = "http://adc.ecinterface/")
public interface NGADCServiceForEC {

	/**
	 * 
	 * @param request
	 * @return returns ecinterface.adc.NGEC
	 */
	@WebMethod(operationName = "AdcServices", action = "http://adc.ecinterface/NGADCServiceForEC/AdcServices")
	@WebResult(name = "AdcServicesResult", targetNamespace = "http://adc.ecinterface/")
	@RequestWrapper(localName = "AdcServices", targetNamespace = "http://adc.ecinterface/", className = "ecinterface.adc.AdcServices")
	@ResponseWrapper(localName = "AdcServicesResponse", targetNamespace = "http://adc.ecinterface/", className = "ecinterface.adc.AdcServicesResponse")
	public NGEC adcServices(
			@WebParam(name = "request", targetNamespace = "http://adc.ecinterface/") NGEC request);

}
